export enum EventType {
  READING_SESSION = 'READING_SESSION',
  DISCUSSION = 'DISCUSSION',
  WORKSHOP = 'WORKSHOP',
  EXHIBITION = 'EXHIBITION',
  FILM_SCREENING = 'FILM_SCREENING',
  OTHER = 'OTHER',
  PAST_ARCHIVE = 'PAST_ARCHIVE',
}
